import json
import re
import os
from difflib import SequenceMatcher

def clean_ocr(text):
    text = re.sub(r'\n+', '\n', text)
    return text.strip()

def extract_vue_text(vue_code):
    if "NOT FOUND" in vue_code or "READ FAILED" in vue_code:
        return ""
    # Remove script block
    vue_code = re.sub(r'<script.*?>.*?</script>', '', vue_code, flags=re.DOTALL)
    # Strip HTML tags but keep some structure
    text = re.sub(r'<[^>]+>', ' ', vue_code)
    # Clean whitespace
    text = re.sub(r'\s+', ' ', text)
    return text.strip()

def detect_tables(ocr_text):
    # Heuristic: if there are multiple lines with lots of numbers/columns
    lines = ocr_text.split('\n')
    table_lines = 0
    for line in lines:
        # If line has multiple numbers or typical table separators
        if len(re.findall(r'\d+', line)) > 3 or '|' in line:
            table_lines += 1
    return table_lines > 3

def has_html_table(vue_code):
    return '<table' in vue_code.lower()

def has_gm_grid(vue_code):
    return '<GmContentGrid' in vue_code

def main():
    json_path = 'audit_results.json'
    out_path = r'C:\Users\mail\.gemini\antigravity-ide\brain\afa3c468-6da5-49d4-95cb-fce3521ddb5f\content_audit_report.md'
    
    with open(json_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
        
    report = ["# 📊 Deep Content Diff Audit Report (Pages 1-15)\n"]
    report.append("> [!INFO]")
    report.append("> This report was auto-generated by running Tesseract OCR on the source images and performing an AST/Regex extraction on the implemented Vue components to detect missing content, structural mismatches, and data inaccuracies.\n")
    
    total_score = 0
    pages_processed = 0
    
    for i in range(1, 16):
        page_key = f"Page_{i}"
        page_data = data.get(page_key, {})
        ocr_raw = page_data.get('ocr', '')
        vue_raw = page_data.get('vue', '')
        
        ocr_clean = clean_ocr(ocr_raw)
        vue_text = extract_vue_text(vue_raw)
        
        status = "✅ PASS"
        issues = []
        
        # 1. Existence Check
        if "NOT FOUND" in vue_raw:
            status = "❌ MISSING COMPONENT"
            issues.append("- **CRITICAL:** `GmPage{}.vue` does not exist on disk!".format(i))
            report.append(f"## Page {i} - {status}")
            report.append("\n".join(issues) + "\n")
            continue
            
        # 2. Similarity Matching
        # We lowercase and remove non-alphanumeric for a rough content match
        ocr_alphanum = re.sub(r'[^a-z0-9]', '', ocr_clean.lower())
        vue_alphanum = re.sub(r'[^a-z0-9]', '', vue_text.lower())
        
        similarity = SequenceMatcher(None, ocr_alphanum, vue_alphanum).ratio()
        
        if similarity < 0.3:
            status = "❌ MAJOR DISCREPANCY"
            issues.append(f"- **Content Mismatch:** The Vue component text matches the OCR image text by only {similarity*100:.1f}%. This indicates significant missing content or placeholder text.")
        elif similarity < 0.6:
            status = "⚠️ PARTIAL MATCH"
            issues.append(f"- **Partial Content:** Similarity is {similarity*100:.1f}%. Some paragraphs or bullet points might be missing.")
        else:
            status = "✅ STRONG MATCH"
            
        total_score += similarity
        pages_processed += 1
            
        # 3. Structural Checks
        image_has_table = detect_tables(ocr_clean)
        code_has_table = has_html_table(vue_raw)
        
        if image_has_table and not code_has_table:
            issues.append("- **Structural Gap:** Image appears to contain a data table, but no `<table>` element was found in the Vue code.")
        
        if not has_gm_grid(vue_raw) and "grid" in ocr_clean.lower():
            issues.append("- **Warning:** Potential missing grid layout. The OCR suggests grid-like data, but `<GmContentGrid>` is missing.")
            
        # Compile page section
        report.append(f"## Page {i} - {status} ({similarity*100:.1f}% Match)")
        if issues:
            report.append("\n".join(issues))
        else:
            report.append("- No major structural or text discrepancies detected.")
            
        report.append("\n### Extracted OCR Sample:")
        report.append("```text\n" + ocr_clean[:200].replace('\n', ' ') + "...\n```")
        report.append("\n---\n")

    avg_score = (total_score / pages_processed) * 100 if pages_processed > 0 else 0
    report.insert(3, f"### Overall Content Integrity Score: **{avg_score:.1f}%**\n")
    
    with open(out_path, 'w', encoding='utf-8') as f:
        f.write("\n".join(report))
        
    print(f"Report generated at {out_path}")

if __name__ == "__main__":
    main()
